### PR TITLE
add esperanto translation

### PR DESCRIPTION
**Pull request by joseluis**
also sorted languages alphabetically in `en.yml`

### CODE REVIEW

**Comment by MichaelThessel** [comment]
Interesting. I have never met anyone speaking Esperanto. According to Wikipedia there are 2 million speakers worldwide. Do you speak it?

**Comment by joseluis** [comment]
Mi parolis ĝin kiam mi estis pli juna, kvankam oni neniam vere forgesas. Mia frato faris la tradukon. Li do parolas ĝin pli. Precipe por la teknikaj terminoj.  :)

`I used it when I was younger, although one never forgets, really. My brother did the translation. He do speaks it more. Specially for the technical terms. :)`

**Comment by MichaelThessel** [comment]
Great stuff. Say thanks to your brother for the translation.

**Comment by joseluis** [comment]
Will do ! thank you!

**Comment by joseluis** [comment]
Ups, do choosing esperanto in the language selector works for you? For me it redirects to english. Maybe I missed something, or maybe it isn't supported by the language module in the framework?

**Comment by MichaelThessel** [comment]
I added eo to the list of valid locales 877e62f08b6adf27ad725d146c62da42e7bd581c

**Comment by joseluis** [comment]
Now it's perfect. Thank you

**Pull request merged**
