### PR TITLE
Add forceSSL-Service with config-option

### PR DESCRIPTION
**Pull request by rabbl**
Issue 7: https://github.com/MichaelThessel/pwx/issues/7
An automatic redirect to https with config-option was needed.
I have implemented a forceSSL-Service with config-option.
Could'nt test this implementation yet.

Improvement could be to use HttpFoundation-Request instead of using $_SERVER
and use HTTPFoundation-Response for the Redirect

### CODE REVIEW

**Comment by MichaelThessel** [comment]
Hi,

Thanks for looking into this. Unfortunately this implementation is not 100% how I would like it to be. I think adding a service is overkill. I would assume that this could be implemented on routing level. 

If we go with the suggested implementation I would need to add

```
$this->forceSSLService->forceSSLIfSet();
```

to every controller action in the future. 

Maybe have a look here:
http://symfony.com/doc/current/cookbook/routing/scheme.html

**Comment by rabbl** [comment]
Ok. That's a good idea. I'll setup a working environment and get into it. 
Another approach could be event-driven, starting the forceSSLService->forceSSLIfSet() on kernel.request. What do you prefer?

**Comment by MichaelThessel** [comment]
I read the Silex documentation. 

Have a look here: http://silex.sensiolabs.org/doc/usage.html#global-configuration

Adding `$app['controllers']->requireHttps()` after the default controller is set [here](https://github.com/MichaelThessel/pwx/blob/master/app/app.php#L54) Should do the trick. We just need a config conditional. Should be only 3 lines in total.

As for defaults. What you did in the previous pull request is good. Default to false, add default true in config.php. And for the Openshift config I would like to set it to true too.

**Comment by rabbl** [comment]
I'll close this pull request. It's replaced by https://github.com/MichaelThessel/pwx/pull/10.

**Pull request closed without merging**
